version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: doce-gestao-postgres
    environment:
      POSTGRES_DB: doce_gestao
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d doce_gestao"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: doce-gestao-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doce_gestao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3636
      SECURITY_JWT_SECRET: 6b586e32723537336b353138356d6a6a3430313233343536373839306162636465666768696a6b6c6d6e6f707172737475767778797a414243444546
    ports:
      - "8080:8080"

volumes:
  postgres_data:
